In [1]:
import pandas as pd

In [ ]:
df = pd.read_excel("pandas_assignment_dataset.xlsx");

df

      Name Education  Marks       City
0     Siva    B.Tech     90  Hyderabad
1     Rama       MBA     45    Chennai
2  Krishna    B.Tech     95  Bangalore
3    Pavan       BBA     88     Mumbai
4    Bhanu       MCA     56      Delhi
5    Vinny       MBA     76       Pune
6    Bobby    B.Tech    100    Kolkata
7   Chinny       BBA     67     Jaipur
8    Kumar       MBA     82      Noida
9      Srk    B.Tech     49  Ahmedabad

In [4]:
#Q1
df.loc[0,'Marks'] = 100

#Q2
df.loc[df['Name'] == 'Rama', 'Education'] = 'M.Tech'


#Q3
df.iloc[-1, -1] = 'Pune'

#Q4
df.iloc[1, -2] = 999

#Q5
df.iloc[2, 0] = 'Raj'

#Q6
df['Marks'] = df['Marks'] + 10

#Q7
df['Marks'] = df['Marks'] * 2


df

     Name Education  Marks       City
0    Siva    B.Tech    220  Hyderabad
1    Rama    M.Tech   2018    Chennai
2     Raj    B.Tech    440  Bangalore
3   Pavan       BBA    412     Mumbai
4   Bhanu       MCA    284      Delhi
5   Vinny       MBA    364       Pune
6   Bobby    B.Tech    460    Kolkata
7  Chinny       BBA    328     Jaipur
8   Kumar       MBA    388      Noida
9     Srk    B.Tech    256       Pune

In [43]:
#Q8
df['DoubleMarks'] = df['Marks'] * 2

#Q9
df['Name'] = df['Name'].str.upper()

#Q10
df['Education'] = df['Education'].str.lower()

#Q11

df['Country'] = 'India';

#Q12

df['Tax'] = df['Marks'] * 0.18;

#Q13
df['Marks'] = df['Marks'] + 5;

#Q14
df['Rank'] = list(range(1,11));

#Q15

df.loc[df['Education']=="mba", 'Education'] = 'MASTER';

#Q16
df['Grade'] = ['A','B', 'C','D','E', 'F', 'G','H', 'I', 'J']

#Q17
city = df['City'].tolist();

df['City'] = city;

#Q18

remarks = ["Good", "Bad", "Average", "Very Good", "Excellent"];
new = [];
from random import choice
import numpy as np
for i in range(1,11):
    new.append(choice(remarks));

df['Remarks'] = new;

#Q19
numbers = [1,2,3,4,5,6,7];
lucky_numbers = [];
for i in range(1,11):
    lucky_numbers.append(choice(numbers));

df['LuckyNumber'] = lucky_numbers;

#Q20
res = ["Pass", "Fail"];
results = [];
for i in range(1,11):
    results.append(choice(res));

df['Result'] = results;

#Q21
df.loc[df['Marks']<50, 'Result'] = 'Fail'

#Q22
df.loc[df['Marks']>=50, 'Result'] = 'Pass'

#Q23
df.loc[df['Marks']>95, 'Result'] = 'Topper'

#Q24
df.loc[(df['Marks']>90) & (df['Marks']<100) , 'Result'] = 'Excellent';

#Q25
df.loc[(df['Marks']>90)&(df['Education']=='b.tech'), 'Education'] = 'BTECH';

df

,Name,Education,Marks,City,DoubleMarks,Country,Tax,Rank,Grade,Remarks,LuckyNumber,Result
0,SIVA,btech,370,Hyderabad,730,India,65.70,1,A,Very Good,2,Topper
1,RAMA,m.tech,2168,Chennai,4326,India,389.34,2,B,Excellent,4,Topper
2,RAJ,btech,590,Bangalore,1170,India,105.30,3,C,Good,4,Topper
3,PAVAN,bba,562,Mumbai,1114,India,100.26,4,D,Excellent,6,Topper
4,BHANU,mca,434,Delhi,858,India,77.22,5,E,Very Good,7,Topper
5,VINNY,master,514,Pune,1018,India,91.62,6,F,Bad,4,Topper
6,BOBBY,btech,610,Kolkata,1210,India,108.90,7,G,Very Good,5,Topper
7,CHINNY,bba,478,Jaipur,946,India,85.14,8,H,Bad,5,Topper
8,KUMAR,master,538,Noida,1066,India,95.94,9,I,Very Good,4,Topper
9,SRK,btech,406,Pune,802,India,72.18,10,J,Average,7,Topper