In [2]:
import pandas as pd

In [27]:
df = pd.DataFrame({'city':["Hyd","Hyd","Hyd","Hyd","Hyd","Chennai"]})
df
print(df['city'].unique().tolist());
print(df['city'].value_counts());

print("Number of Values in column" , len(df['city']));

df['city'].value_counts()/len(df['city'])

mapping = {"Hyd": (df['city'].value_counts()/len(df['city'])).loc['Hyd'],
           "Chennai": (df['city'].value_counts()/len(df['city'])).loc['Chennai']};

df['city'] = df['city'].map(mapping);
df

['Hyd', 'Chennai']
city
Hyd        5
Chennai    1
Name: count, dtype: int64
Number of Values in column 6

       city
0  0.833333
1  0.833333
2  0.833333
3  0.833333
4  0.833333
5  0.166667

In [ ]:
df = pd.DataFrame({
    'city': [
        'Hyderabad',
        'Mumbai',
        'Hyderabad',
        'Delhi',
        'Mumbai',
        'Hyderabad',
        'Pune',
        'Delhi',
        'Mumbai',
        'Hyderabad'
    ]
})
df['city'].unique().tolist();
df['city'] = df['city'].map(df['city'].value_counts()/len(df['city']));
df

   city
0   0.4
1   0.3
2   0.4
3   0.2
4   0.3
5   0.4
6   0.1
7   0.2
8   0.3
9   0.4